//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Submission()
        {
            this.Disabilities = new HashSet<Disability>();
        }
    
        public int SubmissionId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> PreferredPronounsId { get; set; }
        public int LevelOfStudyId { get; set; }
        public bool IsInternationalStudent { get; set; }
        public string AdditionalRequirements { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual LevelsOfStudy LevelsOfStudy { get; set; }
        public virtual PreferredPronoun PreferredPronoun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disability> Disabilities { get; set; }
    }
}
